version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pofile
    ports:
      - "3307:3306"
    volumes:
      - ./data/profile:/docker-entrypoint-initdb.d
  spring-boot:
    build: ./demo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/profile
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql
  nextjs:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot
